#
# Copyright (c) 2023 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
[package]
authors = [
  "Gabriele Baldoni <gabriele.baldoni@zettascale.tech>",
  "Julien Enoch <julien@enoch.fr>",
  "Luca Cominardi <luca.cominardi@zettascale.tech>",
  "Olivier Hécart <olivier.hecart@zettascale.tech>",
  "Pierre Avital <pierre.avital@zettascale.tech>",
  "kydos <angelo@icorsaro.net>",
]
categories = { workspace = true }
description = "Internal crate for zenoh."
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
name = "zenoh-link-ws"
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
uring = []

[dependencies]
async-trait = { workspace = true }
tracing = { workspace = true }
zenoh-core = { workspace = true }
zenoh-link-commons = { workspace = true }
zenoh-protocol = { workspace = true }
zenoh-result = { workspace = true }

[target.'cfg(not(all(target_family = "wasm", target_os = "unknown")))'.dependencies]
futures-util = { workspace = true, features = ["sink", "std"] }
tokio = { workspace = true, features = [
  "io-std",
  "macros",
  "net",
  "rt-multi-thread",
  "time",
] }
tokio-tungstenite = { workspace = true }
tokio-util = { workspace = true, features = ["rt"] }
url = { workspace = true }
zenoh-runtime = { workspace = true }
zenoh-util = { workspace = true }

[target.'cfg(all(target_family = "wasm", target_os = "unknown"))'.dependencies]
flume = { workspace = true }
js-sys = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true, features = [
  "BinaryType",
  "CloseEvent",
  "ErrorEvent",
  "Event",
  "MessageEvent",
  "WebSocket",
] }
